### ISSUE TITLE
why do you use GCP Pubsub

### ISSUE THREAD

**Issue by MaryLilian** [JoseRamirezAyala/SpringBoot-GCP-PUBSUB#1]
Hi, I am reading your project and I love this project
I have a question, why do you choose GCP Pubsub in your project instead of others like RabbitMQ or Kafka, are there any special features that others dont have it. Can you share me it. I am wondering when I should choose GCP Pubsub instead of others like RabbitMQ or Kafka

**Comment by JoseRamirezAyala** [comment]
Hi @MaryLilian, thanks for your comment I'm glad you liked this project!

For your question, I think Apache Kafka and RabbitMQ are better choices if you are not using the GCP stack in your project, both of the technologies have a complete dashboard and an easy way to configure the message producers and subscribers. One of the features I identified from GCP PUB/SUB is how easy is to create a topic and connect a subscriber to the topic by using Google SDK command lines. I definitely recommend you to test it yourself! 

Here is a full-stack project I coded recently to test how fast does messaging work and I was able to see that messages in GCP PUB/SUB work fast and smooth.

Full stack GCP PUB/SUB App: https://github.com/JoseRamirezAyala/GCP-PUB-SUB-FULLSTACK-APP

Here is a GCP tutorial I followed to understand how it works: https://cloud.google.com/pubsub/docs/publish-receive-messages-client-library

Please let me know if you have further questions.

**Comment by JoseRamirezAyala** [comment]
Hi @MaryLilian I forgot to mention one feature from GCP PUB/SUB is that you can easily setup an Apache Beam pipeline with pub/sub functionality to process data continuously.
